name: Test and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Install package
      run: |  
        pip install -e .[test,dev]
        pip show idf2yaml
    
    - name: Lint with flake8 part 1
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Lint with flake8 part 2
      run: |
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check formatting with black
      run: black . --check
    
    - name: Run fast tests with pytest
      run: |
        pytest tests/test_round_trip_fast.py --cov=idf2yaml --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        fail_ci_if_error: true 